-- data.lua : GM command and reference data for GMPanel (Ashita v4).
-- Generated from the project workbook (GM .xlsx). Display/reference only; nothing here is executed
-- except the command strings the user chooses to queue through the chat manager.
-- SQL entries are reference text for an external database tool. GMPanel never runs SQL.

local data = {};

-- Command categories. Each command: cmd (token queued), syntax, args (hint), desc, notes, dangerous.
data.categories = {
    {
        name = 'MOVEMENT & POSITIONING',
        commands = {
            { cmd = '!pos', syntax = '!pos', args = '', desc = 'Print current X/Y/Z, rotation, zone', notes = '', dangerous = false },
            { cmd = '!pos', syntax = '!pos <x> <y> <z>', args = '<x> <y> <z>', desc = 'Teleport to coordinates in current zone', notes = 'Use !pos first to get coords', dangerous = false },
            { cmd = '!posfix', syntax = '!posfix', args = '', desc = 'Reset character to safe ground position', notes = 'Use if stuck in geometry', dangerous = false },
            { cmd = '!goto', syntax = '!goto <name>', args = '<playername>', desc = 'Teleport to player by name', notes = '', dangerous = false },
            { cmd = '!gotoid', syntax = '!gotoid <id>', args = '<charid>', desc = 'Teleport to character by ID', notes = '', dangerous = false },
            { cmd = '!gotoname', syntax = '!gotoname <name>', args = '<name>', desc = 'Search and teleport to named entity (mob/NPC)', notes = '', dangerous = false },
            { cmd = '!bring', syntax = '!bring <name>', args = '<playername>', desc = 'Pull a player to your location', notes = '', dangerous = false },
            { cmd = '!zone', syntax = '!zone <id>', args = '<zoneid>', desc = 'Warp to zone by ID', notes = 'See Zone IDs tab', dangerous = false },
            { cmd = '!homepoint', syntax = '!homepoint', args = '', desc = 'Warp to last home point', notes = '', dangerous = false },
            { cmd = '!gmhome', syntax = '!gmhome', args = '', desc = 'Teleport to GM home (RuLude Gardens by default)', notes = '', dangerous = false },
            { cmd = '!return', syntax = '!return', args = '', desc = 'Return to previous zone', notes = '', dangerous = false },
            { cmd = '!speed', syntax = '!speed <n>', args = '<1-100>', desc = 'Set movement speed multiplier', notes = '0 = default', dangerous = false },
            { cmd = '!hide', syntax = '!hide', args = '', desc = 'Toggle invisibility to other players', notes = '', dangerous = false },
            { cmd = '!up', syntax = '!up <n>', args = '<distance>', desc = 'Move N units upward', notes = 'Useful for ledge access', dangerous = false },
            { cmd = '!down', syntax = '!down <n>', args = '<distance>', desc = 'Move N units downward', notes = '', dangerous = false },
            { cmd = '!where', syntax = '!where', args = '', desc = 'Print player and target positions', notes = '', dangerous = false },
            { cmd = '!cansee', syntax = '!cansee', args = '', desc = 'Check line of sight to current target', notes = '', dangerous = false },
            { cmd = '!inwater', syntax = '!inwater', args = '', desc = 'Check if currently in water', notes = '', dangerous = false },
        },
    },
    {
        name = 'CHARACTER STATE',
        commands = {
            { cmd = '!setplayerlevel', syntax = '!setplayerlevel <n>', args = '<1-99>', desc = 'Set main job level', notes = 'LSB caps at 99; ASB at 75', dangerous = false },
            { cmd = '!changejob', syntax = '!changejob <code>', args = '<3-letter>', desc = 'Switch main job', notes = 'See Job Codes tab', dangerous = false },
            { cmd = '!changesjob', syntax = '!changesjob <code>', args = '<3-letter>', desc = 'Switch support job', notes = '', dangerous = false },
            { cmd = '!masterjob', syntax = '!masterjob', args = '', desc = 'Master the current job', notes = '', dangerous = false },
            { cmd = '!capallskills', syntax = '!capallskills', args = '', desc = 'Cap all skills for the current job/level', notes = '', dangerous = false },
            { cmd = '!capskill', syntax = '!capskill <skill> <n>', args = '<skillname> <level>', desc = 'Set specific skill level', notes = '', dangerous = false },
            { cmd = '!setskill', syntax = '!setskill <skill> <n>', args = '<id> <level>', desc = 'Set skill by ID', notes = '', dangerous = false },
            { cmd = '!hp', syntax = '!hp <n>', args = '<value>', desc = 'Set current HP', notes = '', dangerous = false },
            { cmd = '!mp', syntax = '!mp <n>', args = '<value>', desc = 'Set current MP', notes = '', dangerous = false },
            { cmd = '!tp', syntax = '!tp <n>', args = '<value>', desc = 'Set TP (3000 = full bar)', notes = '', dangerous = false },
            { cmd = '!immortal', syntax = '!immortal', args = '', desc = 'Toggle invincibility (no damage taken)', notes = '', dangerous = false },
            { cmd = '!godmode', syntax = '!godmode', args = '', desc = 'Higher-tier invincibility + auto-MP', notes = '', dangerous = false },
            { cmd = '!raise', syntax = '!raise', args = '', desc = 'Self-raise after KO', notes = 'May not work while KO\'d; use Home Point', dangerous = false },
            { cmd = '!release', syntax = '!release', args = '', desc = 'Release from event/cutscene state', notes = '', dangerous = false },
            { cmd = '!reset', syntax = '!reset', args = '', desc = 'Reset character state (cures debuffs etc.)', notes = '', dangerous = false },
            { cmd = '!stun', syntax = '!stun', args = '', desc = 'Stun target', notes = '', dangerous = false },
            { cmd = '!setplayermodel', syntax = '!setplayermodel <id>', args = '<modelid>', desc = 'Change character model', notes = '', dangerous = false },
            { cmd = '!setplayernation', syntax = '!setplayernation <id>', args = '<1=Sandy 2=Bastok 3=Windy>', desc = 'Change starting nation allegiance', notes = '', dangerous = false },
            { cmd = '!racechange', syntax = '!racechange <id>', args = '<race id>', desc = 'Change race', notes = '1=HumeM 2=HumeF 3=ElvM 4=ElvF 5=TaruM 6=TaruF 7=Mithra 8=Galka', dangerous = false },
            { cmd = '!setrank', syntax = '!setrank <n>', args = '<1-10>', desc = 'Set nation rank', notes = '', dangerous = false },
            { cmd = '!chocobo', syntax = '!chocobo <n>', args = '<minutes>', desc = 'Mount chocobo for N minutes', notes = '', dangerous = false },
            { cmd = '!mount', syntax = '!mount <id>', args = '<mountid>', desc = 'Summon mount', notes = '', dangerous = false },
        },
    },
    {
        name = 'ITEMS & CURRENCY',
        commands = {
            { cmd = '!additem', syntax = '!additem <id> <qty>', args = '<itemid> <count>', desc = 'Add item to inventory by ID', notes = 'Query item_basic', dangerous = false },
            { cmd = '!giveitem', syntax = '!giveitem <name>', args = '<name> [qty]', desc = 'Add item by name', notes = '', dangerous = false },
            { cmd = '!delitem', syntax = '!delitem <id>', args = '<itemid>', desc = 'Remove item by ID', notes = '', dangerous = false },
            { cmd = '!setgil', syntax = '!setgil <n>', args = '<amount>', desc = 'Set gil total', notes = '', dangerous = false },
            { cmd = '!givegil', syntax = '!givegil <n>', args = '<amount>', desc = 'Add gil', notes = '', dangerous = false },
            { cmd = '!takegil', syntax = '!takegil <n>', args = '<amount>', desc = 'Remove gil', notes = '', dangerous = false },
            { cmd = '!addkeyitem', syntax = '!addkeyitem <id>', args = '<keyitemid>', desc = 'Grant a key item', notes = '', dangerous = false },
            { cmd = '!delkeyitem', syntax = '!delkeyitem <id>', args = '<keyitemid>', desc = 'Remove key item', notes = '', dangerous = false },
            { cmd = '!hasitem', syntax = '!hasitem <id>', args = '<itemid>', desc = 'Check if you have item', notes = '', dangerous = false },
            { cmd = '!haskeyitem', syntax = '!haskeyitem <id>', args = '<keyitemid>', desc = 'Check if you have key item', notes = '', dangerous = false },
            { cmd = '!setbag', syntax = '!setbag <bag> <size>', args = '<bagname> <newsize>', desc = 'Resize inventory container', notes = '', dangerous = false },
            { cmd = '!addfish', syntax = '!addfish', args = '', desc = 'Add a fishing catch entry', notes = '', dangerous = false },
            { cmd = '!addcurrency', syntax = '!addcurrency <id> <n>', args = '<curr_id> <amount>', desc = 'Add currency (CP, sparks, etc.)', notes = '', dangerous = false },
            { cmd = '!cp', syntax = '!cp <n>', args = '<amount>', desc = 'Add capacity points', notes = '', dangerous = false },
            { cmd = '!setcapacitypoints', syntax = '!setcapacitypoints <n>', args = '<amount>', desc = 'Set CP total', notes = '', dangerous = false },
            { cmd = '!setjobpoints', syntax = '!setjobpoints <n>', args = '<amount>', desc = 'Set job points', notes = '', dangerous = false },
        },
    },
    {
        name = 'UNLOCK BULKS',
        commands = {
            { cmd = '!addallmaps', syntax = '!addallmaps', args = '', desc = 'Grant every map in the game', notes = '', dangerous = false },
            { cmd = '!addallspells', syntax = '!addallspells', args = '', desc = 'Grant every spell', notes = '', dangerous = false },
            { cmd = '!addalltrusts', syntax = '!addalltrusts', args = '', desc = 'Grant every trust permit', notes = 'See Trusts tab', dangerous = false },
            { cmd = '!addallwarps', syntax = '!addallwarps', args = '', desc = 'Grant every warp destination', notes = '', dangerous = false },
            { cmd = '!addallweaponskills', syntax = '!addallweaponskills', args = '', desc = 'Grant all weapon skills', notes = '', dangerous = false },
            { cmd = '!addallmounts', syntax = '!addallmounts', args = '', desc = 'Grant all mounts', notes = '', dangerous = false },
            { cmd = '!addallmonstrosity', syntax = '!addallmonstrosity', args = '', desc = 'Unlock all monstrosity species', notes = '', dangerous = false },
            { cmd = '!addallatma', syntax = '!addallatma', args = '', desc = 'Grant every Abyssea atma', notes = '', dangerous = false },
            { cmd = '!addallattachments', syntax = '!addallattachments', args = '', desc = 'Grant every Puppetmaster attachment', notes = '', dangerous = false },
        },
    },
    {
        name = 'MOBS & COMBAT',
        commands = {
            { cmd = '!spawnmob', syntax = '!spawnmob <id>', args = '<mobid>', desc = 'Spawn a mob at your location', notes = 'Query mob_pools / mob_spawn_points', dangerous = false },
            { cmd = '!despawnmob', syntax = '!despawnmob', args = '', desc = 'Despawn the targeted mob', notes = '', dangerous = false },
            { cmd = '!mobhere', syntax = '!mobhere <name>', args = '<name>', desc = 'Spawn named mob at your location', notes = '', dangerous = false },
            { cmd = '!npchere', syntax = '!npchere <name>', args = '<name>', desc = 'Spawn NPC at your location', notes = '', dangerous = false },
            { cmd = '!setmoblevel', syntax = '!setmoblevel <n>', args = '<level>', desc = 'Set targeted mob\'s level', notes = '', dangerous = false },
            { cmd = '!setmobflags', syntax = '!setmobflags <flags>', args = '<bitmask>', desc = 'Modify mob behavior flags', notes = '', dangerous = false },
            { cmd = '!setmobmod', syntax = '!setmobmod <id> <val>', args = '<mod> <value>', desc = 'Set mob modifier', notes = '', dangerous = false },
            { cmd = '!getmobflags', syntax = '!getmobflags', args = '', desc = 'Read targeted mob\'s flags', notes = '', dangerous = false },
            { cmd = '!getmobmod', syntax = '!getmobmod <id>', args = '<mod>', desc = 'Read targeted mob\'s modifier', notes = '', dangerous = false },
            { cmd = '!getmobaction', syntax = '!getmobaction', args = '', desc = 'Get current AI action of target', notes = '', dangerous = false },
            { cmd = '!mobskill', syntax = '!mobskill <id>', args = '<skillid>', desc = 'Force targeted mob to use a skill', notes = 'Useful for SCVoice triggers', dangerous = false },
            { cmd = '!mobsub', syntax = '!mobsub <id>', args = '<subid>', desc = 'Change mob skin/family', notes = '', dangerous = false },
            { cmd = '!provokeall', syntax = '!provokeall', args = '', desc = 'Pull aggro from all nearby mobs', notes = '', dangerous = false },
            { cmd = '!getenmity', syntax = '!getenmity', args = '', desc = 'Print enmity table for target', notes = '', dangerous = false },
            { cmd = '!getpool', syntax = '!getpool <id>', args = '<poolid>', desc = 'Look up mob_pool by ID', notes = '', dangerous = false },
            { cmd = '!getspecies', syntax = '!getspecies', args = '', desc = 'Get species of target', notes = '', dangerous = false },
            { cmd = '!getfamily', syntax = '!getfamily', args = '', desc = 'Get family of target', notes = '', dangerous = false },
        },
    },
    {
        name = 'PETS, TRUSTS, FELLOWS',
        commands = {
            { cmd = '!trustengage', syntax = '!trustengage <id>', args = '<spellid>', desc = 'Spawn a trust by spell ID', notes = 'See Trusts tab', dangerous = false },
            { cmd = '!petgodmode', syntax = '!petgodmode', args = '', desc = 'Toggle pet invincibility', notes = '', dangerous = false },
            { cmd = '!pettp', syntax = '!pettp <n>', args = '<value>', desc = 'Set pet TP', notes = '', dangerous = false },
            { cmd = '!gettp', syntax = '!gettp', args = '', desc = 'Get player TP', notes = '', dangerous = false },
        },
    },
    {
        name = 'ENVIRONMENT',
        commands = {
            { cmd = '!setweather', syntax = '!setweather <id>', args = '<weatherid>', desc = 'Force weather state in current zone', notes = 'See Weather IDs tab', dangerous = false },
            { cmd = '!time', syntax = '!time <hour>', args = '<0-23>', desc = 'Set game-time hour', notes = '', dangerous = false },
            { cmd = '!addtime', syntax = '!addtime <h>', args = '<hours>', desc = 'Advance game time', notes = '', dangerous = false },
            { cmd = '!setmusic', syntax = '!setmusic <type> <bgmid>', args = '<idletype> <bgmid>', desc = 'Force zone BGM', notes = 'Critical for ZoneMusic testing', dangerous = false },
            { cmd = '!resetlights', syntax = '!resetlights', args = '', desc = 'Reset moon/sun light values', notes = '', dangerous = false },
            { cmd = '!uptime', syntax = '!uptime', args = '', desc = 'Show server uptime', notes = '', dangerous = false },
            { cmd = '!updateconquest', syntax = '!updateconquest', args = '', desc = 'Force conquest update tick', notes = '', dangerous = false },
        },
    },
    {
        name = 'MISSIONS / QUESTS / TITLES',
        commands = {
            { cmd = '!addmission', syntax = '!addmission <log> <id>', args = '<logid> <missionid>', desc = 'Start a mission', notes = '', dangerous = false },
            { cmd = '!completemission', syntax = '!completemission <log> <id>', args = '<logid> <missionid>', desc = 'Complete a mission', notes = '', dangerous = false },
            { cmd = '!delmission', syntax = '!delmission <log> <id>', args = '<logid> <missionid>', desc = 'Remove mission progress', notes = '', dangerous = false },
            { cmd = '!checkmission', syntax = '!checkmission <log> <id>', args = '<logid> <missionid>', desc = 'Check mission status', notes = '', dangerous = false },
            { cmd = '!setmissionstatus', syntax = '!setmissionstatus <log> <stat>', args = '<logid> <status>', desc = 'Set mission stage status', notes = '', dangerous = false },
            { cmd = '!addquest', syntax = '!addquest <log> <id>', args = '<logid> <questid>', desc = 'Start a quest', notes = '', dangerous = false },
            { cmd = '!completequest', syntax = '!completequest <log> <id>', args = '<logid> <questid>', desc = 'Complete a quest', notes = '', dangerous = false },
            { cmd = '!delquest', syntax = '!delquest <log> <id>', args = '<logid> <questid>', desc = 'Remove quest progress', notes = '', dangerous = false },
            { cmd = '!checkquest', syntax = '!checkquest <log> <id>', args = '<logid> <questid>', desc = 'Check quest status', notes = '', dangerous = false },
            { cmd = '!setquestvar', syntax = '!setquestvar <log> <q> <v> <n>', args = '', desc = 'Set quest variable', notes = '', dangerous = false },
            { cmd = '!getquestvar', syntax = '!getquestvar <log> <q> <v>', args = '', desc = 'Read quest variable', notes = '', dangerous = false },
            { cmd = '!addtitle', syntax = '!addtitle <id>', args = '<titleid>', desc = 'Grant title', notes = '', dangerous = false },
            { cmd = '!hastitle', syntax = '!hastitle <id>', args = '<titleid>', desc = 'Check if you own title', notes = '', dangerous = false },
        },
    },
    {
        name = 'FAME / GAME PROGRESS',
        commands = {
            { cmd = '!setfamelevel', syntax = '!setfamelevel <area> <n>', args = '<area> <level>', desc = 'Set fame in a city/area', notes = '', dangerous = false },
            { cmd = '!getfame', syntax = '!getfame', args = '', desc = 'Show all fame levels', notes = '', dangerous = false },
            { cmd = '!cnation', syntax = '!cnation', args = '', desc = 'Show conquest standing', notes = '', dangerous = false },
            { cmd = '!setallegiance', syntax = '!setallegiance <n>', args = '<id>', desc = 'Set Adoulin allegiance', notes = '', dangerous = false },
        },
    },
    {
        name = 'EFFECTS / STATUS',
        commands = {
            { cmd = '!addeffect', syntax = '!addeffect <id> <pwr> <dur>', args = '<effect> <power> <seconds>', desc = 'Apply status effect', notes = 'See Status Effects tab', dangerous = false },
            { cmd = '!deleffect', syntax = '!deleffect <id>', args = '<effectid>', desc = 'Remove status effect', notes = '', dangerous = false },
            { cmd = '!geteffects', syntax = '!geteffects', args = '', desc = 'List active status effects on target', notes = '', dangerous = false },
        },
    },
    {
        name = 'CHOCOBO RAISING',
        commands = {
            { cmd = '!chocoboraising', syntax = '!chocoboraising', args = '', desc = 'Open chocobo raising menu', notes = '', dangerous = false },
        },
    },
    {
        name = 'WEAPONSKILL POINTS',
        commands = {
            { cmd = '!addweaponskillpoints', syntax = '!addweaponskillpoints <n>', args = '<amount>', desc = 'Add WS points to currently equipped WS', notes = '', dangerous = false },
            { cmd = '!getwspoints', syntax = '!getwspoints', args = '', desc = 'Show current weaponskill points', notes = '', dangerous = false },
        },
    },
    {
        name = 'EVENT / CUTSCENE',
        commands = {
            { cmd = '!cs', syntax = '!cs <id>', args = '<csid>', desc = 'Play a cutscene', notes = '', dangerous = false },
            { cmd = '!cs2', syntax = '!cs2 <id>', args = '<csid>', desc = 'Play a cutscene (variant)', notes = '', dangerous = false },
            { cmd = '!animation', syntax = '!animation <id>', args = '<animid>', desc = 'Trigger character animation', notes = '', dangerous = false },
            { cmd = '!animatenpc', syntax = '!animatenpc <name> <anim>', args = '', desc = 'Trigger NPC animation', notes = '', dangerous = false },
            { cmd = '!entityvisual', syntax = '!entityvisual', args = '', desc = 'Cycle target\'s visual flags', notes = '', dangerous = false },
            { cmd = '!menu', syntax = '!menu <id>', args = '<menuid>', desc = 'Open a menu', notes = '', dangerous = false },
        },
    },
    {
        name = 'BCNM / INSTANCES',
        commands = {
            { cmd = '!instance', syntax = '!instance <id>', args = '<instanceid>', desc = 'Enter an instance', notes = '', dangerous = false },
            { cmd = '!checkinstance', syntax = '!checkinstance', args = '', desc = 'Check current instance state', notes = '', dangerous = false },
            { cmd = '!reloadbattlefield', syntax = '!reloadbattlefield', args = '', desc = 'Reload BCNM/battlefield data', notes = '', dangerous = false },
            { cmd = '!setbattlefieldtime', syntax = '!setbattlefieldtime <s>', args = '<seconds>', desc = 'Set BCNM remaining time', notes = '', dangerous = false },
        },
    },
    {
        name = 'INSPECTION / DEBUG',
        commands = {
            { cmd = '!getstats', syntax = '!getstats', args = '', desc = 'Dump character stats', notes = '', dangerous = false },
            { cmd = '!getid', syntax = '!getid', args = '', desc = 'Get target entity ID', notes = '', dangerous = false },
            { cmd = '!getskill', syntax = '!getskill <id>', args = '<skillid>', desc = 'Check skill level', notes = '', dangerous = false },
            { cmd = '!getmod', syntax = '!getmod <id>', args = '<modifier>', desc = 'Check modifier value', notes = '', dangerous = false },
            { cmd = '!getfishers', syntax = '!getfishers', args = '', desc = 'Show active fishers', notes = '', dangerous = false },
            { cmd = '!getlocalvars', syntax = '!getlocalvars', args = '', desc = 'List local vars on target', notes = '', dangerous = false },
            { cmd = '!getprevzoneline', syntax = '!getprevzoneline', args = '', desc = 'Get previous zone line entry', notes = '', dangerous = false },
            { cmd = '!getta', syntax = '!getta', args = '', desc = 'Get target of target\'s target', notes = '', dangerous = false },
            { cmd = '!checklocalvar', syntax = '!checklocalvar <var>', args = '<varname>', desc = 'Read local var', notes = '', dangerous = false },
            { cmd = '!checkvar', syntax = '!checkvar <var>', args = '<varname>', desc = 'Read char var', notes = '', dangerous = false },
            { cmd = '!checkinteraction', syntax = '!checkinteraction <id>', args = '<id>', desc = 'Check interaction state', notes = '', dangerous = false },
            { cmd = '!setlocalvar', syntax = '!setlocalvar <var> <n>', args = '<name> <value>', desc = 'Set local var', notes = '', dangerous = false },
            { cmd = '!setplayervar', syntax = '!setplayervar <var> <n>', args = '<name> <value>', desc = 'Set char var', notes = '', dangerous = false },
        },
    },
    {
        name = 'UTILITY',
        commands = {
            { cmd = '!togglegm', syntax = '!togglegm', args = '', desc = 'Show/hide GM nameflag icon', notes = '', dangerous = false },
            { cmd = '!exec', syntax = '!exec <lua>', args = '<luacode>', desc = 'Execute arbitrary Lua on server', notes = 'Most powerful command — careful', dangerous = true },
            { cmd = '!send', syntax = '!send <player> <command>', args = '<name> <cmd>', desc = 'Run command as another player', notes = '', dangerous = false },
            { cmd = '!reloadglobal', syntax = '!reloadglobal', args = '', desc = 'Reload global Lua scripts', notes = 'Use after editing scripts', dangerous = false },
            { cmd = '!reloadquest', syntax = '!reloadquest <area>', args = '<area>', desc = 'Reload quest area scripts', notes = '', dangerous = false },
            { cmd = '!reloadinteraction', syntax = '!reloadinteraction', args = '', desc = 'Reload interaction system', notes = '', dangerous = false },
            { cmd = '!reloadnavmesh', syntax = '!reloadnavmesh', args = '', desc = 'Reload navmesh data', notes = 'After dropping in new navmesh files', dangerous = false },
            { cmd = '!reloadmagians', syntax = '!reloadmagians', args = '', desc = 'Reload Magian trial data', notes = '', dangerous = false },
            { cmd = '!reloaddefaultactions', syntax = '!reloaddefaultactions', args = '', desc = 'Reload default action data', notes = '', dangerous = false },
            { cmd = '!reloadrecipes', syntax = '!reloadrecipes', args = '', desc = 'Reload synthesis recipes', notes = '', dangerous = false },
            { cmd = '!rebuildnavmesh', syntax = '!rebuildnavmesh', args = '', desc = 'Trigger navmesh rebuild', notes = '', dangerous = false },
            { cmd = '!build', syntax = '!build', args = '', desc = 'Show build info', notes = '', dangerous = false },
            { cmd = '!ah', syntax = '!ah', args = '', desc = 'Open auction house anywhere', notes = '', dangerous = false },
            { cmd = '!rename', syntax = '!rename <newname>', args = '<charname>', desc = 'Rename character', notes = '', dangerous = false },
            { cmd = '!sleep', syntax = '!sleep <n>', args = '<seconds>', desc = 'Sleep server (debug)', notes = '', dangerous = true },
            { cmd = '!crash', syntax = '!crash', args = '', desc = 'Deliberately crash map server', notes = 'DANGER: Use only for crash recovery testing', dangerous = true },
            { cmd = '!logoff', syntax = '!logoff', args = '', desc = 'Disconnect player', notes = '', dangerous = false },
        },
    },
    {
        name = 'MODERATION (HIGH PRIV)',
        commands = {
            { cmd = '!jail', syntax = '!jail <name> <hours>', args = '<player> <hours>', desc = 'Jail a player', notes = '', dangerous = true },
            { cmd = '!pardon', syntax = '!pardon <name>', args = '<player>', desc = 'Release from jail', notes = '', dangerous = true },
            { cmd = '!afkcheck', syntax = '!afkcheck', args = '', desc = 'Check AFK status of players', notes = '', dangerous = true },
            { cmd = '!yell', syntax = '!yell <message>', args = '<text>', desc = 'Server-wide yell', notes = '', dangerous = true },
            { cmd = '!breaklinkshell', syntax = '!breaklinkshell <id>', args = '<lsid>', desc = 'Break a linkshell', notes = '', dangerous = true },
            { cmd = '!givels', syntax = '!givels <name> <id>', args = '<player> <ls>', desc = 'Give a linkshell to a player', notes = '', dangerous = true },
        },
    },
    {
        name = 'FUN / VANITY',
        commands = {
            { cmd = '!costume', syntax = '!costume <id>', args = '<modelid>', desc = 'Apply costume', notes = '', dangerous = false },
            { cmd = '!costume2', syntax = '!costume2 <id>', args = '<modelid>', desc = 'Costume (variant)', notes = '', dangerous = false },
            { cmd = '!hide', syntax = '!hide', args = '', desc = 'Toggle visibility', notes = '', dangerous = false },
            { cmd = '!wallhack', syntax = '!wallhack', args = '', desc = 'Toggle collision (walk through walls)', notes = '', dangerous = false },
            { cmd = '!posemannequin', syntax = '!posemannequin', args = '', desc = 'Pose mannequins', notes = '', dangerous = false },
        },
    },
};

-- Reference tables. columns = header labels; rows = { group, cells }; use = index of the cell that
-- the "Use" button copies into the shared argument field (nil = no Use button); copy = index of the
-- cell the "Copy" button places on the clipboard.
data.references = {
    {
        name = 'Zones',
        note = 'Zone IDs for !zone <id> and !setmusic. Placeholder IDs from the workbook are omitted.',
        columns = { 'ID', 'Zone Name', 'World' },
        widths = { 50, 260, 90 },
        use = 1,
        copy = 1,
        rows = {
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '86', 'Everbloom Hollow', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '93', 'Ruhotz Silvermines', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '100', 'West Ronfaure', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '101', 'East Ronfaure', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '102', 'La Theine Plateau', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '103', 'Valkurm Dunes', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '104', 'Jugner Forest', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '105', 'Batallia Downs', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '106', 'North Gustaberg', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '107', 'South Gustaberg', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '108', 'Konschtat Highlands', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '109', 'Pashhow Marshlands', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '110', 'Rolanberry Fields', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '111', 'Beaucedine Glacier', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '112', 'Xarcabard', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '113', 'Cape Teriggan', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '114', 'Eastern Altepa Desert', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '115', 'West Sarutabaruta', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '116', 'East Sarutabaruta', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '117', 'Tahrongi Canyon', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '118', 'Buburimu Peninsula', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '119', 'Meriphataud Mountains', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '120', 'Sauromugue Champaign', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '121', 'Sanctuary of Zi\'Tah', '' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '122', 'RoMaeve', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '123', 'Yuhtunga Jungle', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '124', 'Yhoator Jungle', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '125', 'Western Altepa Desert', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '126', 'Qufim Island', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '127', 'Behemoths Dominion', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '128', 'Valley of Sorrows', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '129', 'Ghoyus Reverie', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '130', 'RuAun Gardens', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '131', 'Mordion Gaol', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '139', 'Horlais Peak', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '140', 'Ghelsba Outpost', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '141', 'Fort Ghelsba', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '142', 'Yughott Grotto', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '143', 'Palborough Mines', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '145', 'Giddeus', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '146', 'Balgas Dais', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '147', 'Beadeaux', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '148', 'Qulun Dome', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '149', 'Davoi', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '150', 'Monastic Cavern', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '151', 'Castle Oztroja', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '152', 'Altar Room', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '153', 'The Boyahda Tree', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '154', 'Dragons Aery', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '157', 'Middle Delkfutts Tower', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '158', 'Upper Delkfutts Tower', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '159', 'Temple of Uggalepih', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '160', 'Den of Rancor', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '161', 'Castle Zvahl Baileys', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '162', 'Castle Zvahl Keep', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '163', 'Sacrificial Chamber', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '166', 'Ranguemont Pass', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '167', 'Bostaunieux Oubliette', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '168', 'Chamber of Oracles', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '169', 'Toraimarai Canal', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '170', 'Full Moon Fountain', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '172', 'Zeruhn Mines', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '173', 'Korroloka Tunnel', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '174', 'Kuftal Tunnel', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '176', 'Sea Serpent Grotto', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '177', 'VeLugannon Palace', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '178', 'The Shrine of RuAvitau', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '179', 'Stellar Fulcrum', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '181', 'The Celestial Nexus', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '184', 'Lower Delkfutts Tower', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '190', 'King Ranperres Tomb', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '191', 'Dangruf Wadi', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '192', 'Inner Horutoto Ruins', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '193', 'Ordelles Caves', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '194', 'Outer Horutoto Ruins', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '195', 'The Eldieme Necropolis', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '196', 'Gusgen Mines', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '197', 'Crawlers Nest', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '198', 'Maze of Shakhrami', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '200', 'Garlaige Citadel', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '201', 'Cloister of Gales', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '202', 'Cloister of Storms', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '203', 'Cloister of Frost', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '204', 'FeiYin', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '205', 'Ifrits Cauldron', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '206', 'QuBia Arena', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '208', 'Quicksand Caves', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '209', 'Cloister of Tremors', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '210', 'GM Home', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '212', 'Gustav Tunnel', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '213', 'Labyrinth of Onzozo', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '214', 'Residential Area', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '219', 'Residential Area', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '221', 'Ship bound for Mhaura', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '222', 'Provenance', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '223', 'San dOria-Jeuno Airship', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '224', 'Bastok-Jeuno Airship', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '225', 'Windurst-Jeuno Airship', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '226', 'Kazham-Jeuno Airship', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '227', 'Ship bound for Selbina Pirates', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '228', 'Ship bound for Mhaura Pirates', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '229', 'Throne Room [V]', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '230', 'Southern San dOria', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '231', 'Northern San dOria', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '232', 'Port San dOria', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '233', 'Chateau dOraguille', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '234', 'Bastok Mines', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '235', 'Bastok Markets', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '236', 'Port Bastok', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '237', 'Metalworks', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '238', 'Windurst Waters', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '239', 'Windurst Walls', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '240', 'Port Windurst', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '241', 'Windurst Woods', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '242', 'Heavens Tower', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '243', 'RuLude Gardens', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '244', 'Upper Jeuno', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '245', 'Lower Jeuno', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '246', 'Port Jeuno', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '247', 'Rabao', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '248', 'Selbina', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '249', 'Mhaura', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '250', 'Kazham', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '251', 'Hall of the Gods', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '252', 'Norg', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '258', 'Rala Waterways', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '259', 'Rala Waterways U', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '269', 'Moh Gates', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '278', 'Gwora-Corridor', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '283', 'Silver Knife', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '285', 'Feretory', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '286', '286', 'Old World' } },
            { group = 'VANILLA / RISE OF THE ZILART', cells = { '290', 'Desuetia Empyreal Paradox', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '2', 'Carpenters Landing', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '3', 'Manaclipper', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '4', 'Bibiki Bay', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '5', 'Uleguerand Range', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '6', 'Bearclaw Pinnacle', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '7', 'Attohwa Chasm', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '8', 'Boneyard Gully', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '9', 'PsoXja', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '10', 'The Shrouded Maw', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '11', 'Oldton Movalpolos', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '13', 'Mine Shaft 2716', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '14', 'Hall of Transference', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '16', 'Promyvion-Holla', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '17', 'Spire of Holla', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '18', 'Promyvion-Dem', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '19', 'Spire of Dem', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '20', 'Promyvion-Mea', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '21', 'Spire of Mea', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '23', 'Spire of Vahzl', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '24', 'Lufaise Meadows', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '25', 'Misareaux Coast', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '26', 'Tavnazian Safehold', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '27', 'Phomiuna Aqueducts', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '28', 'Sacrarium', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '29', 'Riverne-Site B01', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '30', 'Riverne-Site A01', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '31', 'Monarch Linn', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '32', 'Sealions Den', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '33', 'AlTaieu', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '34', 'Grand Palace of HuXzoi', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '35', 'The Garden of RuHmet', 'Old World' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '36', 'Empyreal Paradox', 'Old World' } },
            { group = 'LIMBUS (SEA)', cells = { '37', 'Temenos', 'Old World' } },
            { group = 'LIMBUS (SEA)', cells = { '38', 'Apollyon', 'Old World' } },
            { group = 'DYNAMIS', cells = { '39', 'Dynamis-Valkurm', 'Old World' } },
            { group = 'DYNAMIS', cells = { '40', 'Dynamis-Buburimu', 'Old World' } },
            { group = 'DYNAMIS', cells = { '41', 'Dynamis-Qufim', 'Old World' } },
            { group = 'DYNAMIS', cells = { '42', 'Dynamis-Tavnazia', 'Old World' } },
            { group = 'DYNAMIS', cells = { '134', 'Dynamis-Beaucedine', 'Old World' } },
            { group = 'DYNAMIS', cells = { '135', 'Dynamis-Xarcabard', 'Old World' } },
            { group = 'DYNAMIS', cells = { '185', 'Dynamis-San dOria', 'Old World' } },
            { group = 'DYNAMIS', cells = { '186', 'Dynamis-Bastok', 'Old World' } },
            { group = 'DYNAMIS', cells = { '187', 'Dynamis-Windurst', 'Old World' } },
            { group = 'DYNAMIS', cells = { '188', 'Dynamis-Jeuno', 'Old World' } },
            { group = 'DYNAMIS [D] (REFORGED)', cells = { '294', 'Dynamis-San dOria [D]', 'Old World' } },
            { group = 'DYNAMIS [D] (REFORGED)', cells = { '295', 'Dynamis-Bastok [D]', 'Old World' } },
            { group = 'DYNAMIS [D] (REFORGED)', cells = { '296', 'Dynamis-Windurst [D]', 'Old World' } },
            { group = 'DYNAMIS [D] (REFORGED)', cells = { '297', 'Dynamis-Jeuno [D]', 'Old World' } },
            { group = 'DYNAMIS [D] (REFORGED)', cells = { '299', 'Gwora-Throne Room', 'Old World' } },
            { group = 'SALVAGE / EINHERJAR', cells = { '43', 'Diorama Abdhaljs-Ghelsba', 'Old World' } },
            { group = 'SALVAGE / EINHERJAR', cells = { '44', 'Abdhaljs Isle-Purgonorgo', 'Old World' } },
            { group = 'SALVAGE / EINHERJAR', cells = { '183', 'Maquette Abdhaljs-Legion A', 'Old World' } },
            { group = 'SALVAGE / EINHERJAR', cells = { '287', 'Maquette Abdhaljs-Legion B', 'Old World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '46', 'Open sea route to Al Zahbi', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '47', 'Open sea route to Mhaura', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '48', 'Al Zahbi', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '50', 'Aht Urhgan Whitegate', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '51', 'Wajaom Woodlands', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '52', 'Bhaflau Thickets', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '53', 'Nashmau', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '54', 'Arrapago Reef', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '55', 'Ilrusi Atoll', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '56', 'Periqia', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '57', 'Talacca Cove', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '58', 'Silver Sea route to Nashmau', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '59', 'Silver Sea route to Al Zahbi', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '60', 'The Ashu Talif', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '61', 'Mount Zhayolm', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '62', 'Halvung', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '63', 'Lebros Cavern', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '64', 'Navukgo Execution Chamber', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '65', 'Mamook', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '66', 'Mamool Ja Training Grounds', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '67', 'Jade Sepulcher', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '68', 'Aydeewa Subterrane', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '69', 'Leujaoam Sanctum', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '70', 'Chocobo Circuit', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '71', 'The Colosseum', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '72', 'Alzadaal Undersea Ruins', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '73', 'Zhayolm Remnants', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '74', 'Arrapago Remnants', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '75', 'Bhaflau Remnants', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '76', 'Silver Sea Remnants', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '77', 'Nyzul Isle', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '78', 'Hazhalm Testing Grounds', 'New World' } },
            { group = 'TREASURES OF AHT URHGAN — NEW WORLD (engine plays; addon hands-off)', cells = { '79', 'Caedarva Mire', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '80', 'Southern San dOria [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '81', 'East Ronfaure [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '82', 'Jugner Forest [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '83', 'Vunkerl Inlet [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '84', 'Batallia Downs [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '85', 'La Vaule [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '87', 'Bastok Markets [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '88', 'North Gustaberg [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '89', 'Grauberg [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '90', 'Pashhow Marshlands [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '91', 'Rolanberry Fields [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '92', 'Beadeaux [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '94', 'Windurst Waters [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '95', 'West Sarutabaruta [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '96', 'Fort Karugo-Narugo [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '97', 'Meriphataud Mountains [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '98', 'Sauromugue Champaign [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '99', 'Castle Oztroja [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '136', 'Beaucedine Glacier [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '137', 'Xarcabard [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '138', 'Castle Zvahl Baileys [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '155', 'Castle Zvahl Keep [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '156', 'Throne Room [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '164', 'Garlaige Citadel [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '171', 'Crawlers Nest [S]', 'New World' } },
            { group = 'WINGS OF THE GODDESS [S] — NEW WORLD (engine plays; addon hands-off)', cells = { '175', 'The Eldieme Necropolis [S]', 'New World' } },
            { group = 'ABYSSEA — NEW WORLD (engine plays; addon hands-off)', cells = { '15', 'Abyssea-Konschtat', 'New World' } },
            { group = 'ABYSSEA — NEW WORLD (engine plays; addon hands-off)', cells = { '45', 'Abyssea-Tahrongi', 'New World' } },
            { group = 'ABYSSEA — NEW WORLD (engine plays; addon hands-off)', cells = { '132', 'Abyssea-La Theine', 'New World' } },
            { group = 'ABYSSEA — NEW WORLD (engine plays; addon hands-off)', cells = { '215', 'Abyssea-Attohwa', 'New World' } },
            { group = 'ABYSSEA — NEW WORLD (engine plays; addon hands-off)', cells = { '216', 'Abyssea-Misareaux', 'New World' } },
            { group = 'ABYSSEA — NEW WORLD (engine plays; addon hands-off)', cells = { '217', 'Abyssea-Vunkerl', 'New World' } },
            { group = 'ABYSSEA — NEW WORLD (engine plays; addon hands-off)', cells = { '218', 'Abyssea-Altepa', 'New World' } },
            { group = 'ABYSSEA — NEW WORLD (engine plays; addon hands-off)', cells = { '253', 'Abyssea-Uleguerand', 'New World' } },
            { group = 'ABYSSEA — NEW WORLD (engine plays; addon hands-off)', cells = { '254', 'Abyssea-Grauberg', 'New World' } },
            { group = 'ABYSSEA — NEW WORLD (engine plays; addon hands-off)', cells = { '255', 'Abyssea-Empyreal Paradox', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '133', 'Outer RaKaznar [U2]', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '189', 'Outer RaKaznar [U3]', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '256', 'Western Adoulin', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '257', 'Eastern Adoulin', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '260', 'Yahse Hunting Grounds', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '261', 'Ceizak Battlegrounds', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '262', 'Foret de Hennetiel', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '263', 'Yorcia Weald', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '264', 'Yorcia Weald U', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '265', 'Morimar Basalt Fields', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '266', 'Marjami Ravine', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '267', 'Kamihr Drifts', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '268', 'Sih Gates', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '270', 'Cirdas Caverns', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '271', 'Cirdas Caverns U', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '272', 'Dho Gates', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '273', 'Woh Gates', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '274', 'Outer RaKaznar', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '275', 'Outer RaKaznar [U1]', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '276', 'RaKaznar Inner Court', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '277', 'RaKaznar Turris', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '280', 'Mog Garden', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '281', 'Leafallia', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '282', 'Mount Kamihr', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '284', 'Celennia Memorial Library', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '288', 'Escha ZiTah', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '289', 'Escha RuAun', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '291', 'Reisenjima', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '292', 'Reisenjima Henge', 'New World' } },
            { group = 'SEEKERS OF ADOULIN — NEW WORLD (engine plays; addon hands-off)', cells = { '293', 'Reisenjima Sanctorium', 'New World' } },
            { group = 'WALK OF ECHOES — NEW WORLD (engine plays; addon hands-off)', cells = { '182', 'Walk of Echoes', 'New World' } },
            { group = 'WALK OF ECHOES — NEW WORLD (engine plays; addon hands-off)', cells = { '279', 'Walk of Echoes [P2]', 'New World' } },
            { group = 'WALK OF ECHOES — NEW WORLD (engine plays; addon hands-off)', cells = { '298', 'Walk of Echoes [P1]', 'New World' } },
        },
    },
    {
        name = 'Jobs',
        note = '3-letter job codes for !changejob and !changesjob.',
        columns = { 'Code', 'Job Name', 'Notes' },
        widths = { 50, 140, 260 },
        use = 1,
        copy = 1,
        rows = {
            { group = 'STANDARD JOBS', cells = { 'war', 'Warrior', 'Starting job' } },
            { group = 'STANDARD JOBS', cells = { 'mnk', 'Monk', '' } },
            { group = 'STANDARD JOBS', cells = { 'whm', 'White Mage', 'Starting job' } },
            { group = 'STANDARD JOBS', cells = { 'blm', 'Black Mage', '' } },
            { group = 'STANDARD JOBS', cells = { 'rdm', 'Red Mage', '' } },
            { group = 'STANDARD JOBS', cells = { 'thf', 'Thief', '' } },
            { group = 'STANDARD JOBS', cells = { 'pld', 'Paladin', 'Unlock quest required (or just !changejob)' } },
            { group = 'STANDARD JOBS', cells = { 'drk', 'Dark Knight', '' } },
            { group = 'STANDARD JOBS', cells = { 'bst', 'Beastmaster', 'Your most-developed job' } },
            { group = 'STANDARD JOBS', cells = { 'brd', 'Bard', '' } },
            { group = 'STANDARD JOBS', cells = { 'rng', 'Ranger', '' } },
            { group = 'STANDARD JOBS', cells = { 'sam', 'Samurai', '' } },
            { group = 'STANDARD JOBS', cells = { 'nin', 'Ninja', '' } },
            { group = 'STANDARD JOBS', cells = { 'drg', 'Dragoon', '' } },
            { group = 'STANDARD JOBS', cells = { 'smn', 'Summoner', '' } },
            { group = 'TOAU JOBS', cells = { 'blu', 'Blue Mage', '' } },
            { group = 'TOAU JOBS', cells = { 'cor', 'Corsair', '' } },
            { group = 'TOAU JOBS', cells = { 'pup', 'Puppetmaster', '' } },
            { group = 'WoTG JOBS', cells = { 'dnc', 'Dancer', '' } },
            { group = 'WoTG JOBS', cells = { 'sch', 'Scholar', '' } },
            { group = 'ADOULIN JOBS', cells = { 'geo', 'Geomancer', '' } },
            { group = 'ADOULIN JOBS', cells = { 'run', 'Rune Fencer', '' } },
        },
    },
    {
        name = 'Status Effects',
        note = 'Use with !addeffect <id> <power> <duration_seconds> and !deleffect <id>.',
        columns = { 'ID', 'Effect Name', 'Description', 'Notes' },
        widths = { 50, 120, 200, 180 },
        use = 1,
        copy = 1,
        rows = {
            { group = '', cells = { '33', 'Haste', 'Speeds attack/casting', 'Common buff test' } },
            { group = '', cells = { '34', 'Slow', 'Reduces attack speed', '' } },
            { group = '', cells = { '37', 'Protect', 'Damage reduction', '' } },
            { group = '', cells = { '38', 'Shell', 'Magic damage reduction', '' } },
            { group = '', cells = { '39', 'Regen', 'HP recovery over time', '' } },
            { group = '', cells = { '40', 'Refresh', 'MP recovery over time', '' } },
            { group = '', cells = { '43', 'Stoneskin', 'Damage absorption shell', '' } },
            { group = '', cells = { '44', 'Blink', 'Evade physical attacks', '' } },
            { group = '', cells = { '45', 'Aquaveil', 'Reduces spell interruption', '' } },
            { group = 'DEBUFFS / ENFEEBLING', cells = { '1', 'Sleep', 'Cannot act', 'PartyVoice trigger test' } },
            { group = 'DEBUFFS / ENFEEBLING', cells = { '2', 'Weight', 'Slowed movement', '' } },
            { group = 'DEBUFFS / ENFEEBLING', cells = { '3', 'Bind', 'Cannot move', '' } },
            { group = 'DEBUFFS / ENFEEBLING', cells = { '4', 'Silence', 'Cannot cast', '' } },
            { group = 'DEBUFFS / ENFEEBLING', cells = { '5', 'Petrification', 'Cannot act, defense up', '' } },
            { group = 'DEBUFFS / ENFEEBLING', cells = { '6', 'Stun', 'Brief incapacitation', '' } },
            { group = 'DEBUFFS / ENFEEBLING', cells = { '7', 'Poison', 'DoT', '' } },
            { group = 'DEBUFFS / ENFEEBLING', cells = { '8', 'Paralysis', 'Random action failure', '' } },
            { group = 'DEBUFFS / ENFEEBLING', cells = { '9', 'Blindness', 'Reduced accuracy', '' } },
            { group = 'DEBUFFS / ENFEEBLING', cells = { '10', 'Disease', 'Reduced HP/MP recovery', '' } },
            { group = 'DEBUFFS / ENFEEBLING', cells = { '11', 'Curse', 'Reduced max HP', '' } },
            { group = 'DEBUFFS / ENFEEBLING', cells = { '13', 'Slow', 'Reduced attack speed', '' } },
            { group = 'DEBUFFS / ENFEEBLING', cells = { '16', 'Bio', 'Magic DoT', '' } },
            { group = 'ELEMENTAL DOTS', cells = { '128', 'Burn', 'Fire DoT', '' } },
            { group = 'ELEMENTAL DOTS', cells = { '129', 'Frost', 'Ice DoT', '' } },
            { group = 'ELEMENTAL DOTS', cells = { '130', 'Choke', 'Wind DoT', '' } },
            { group = 'ELEMENTAL DOTS', cells = { '131', 'Rasp', 'Earth DoT', '' } },
            { group = 'ELEMENTAL DOTS', cells = { '132', 'Shock', 'Thunder DoT', '' } },
            { group = 'ELEMENTAL DOTS', cells = { '133', 'Drown', 'Water DoT', '' } },
            { group = 'SPECIAL STATES', cells = { '14', 'Sleep II', 'Higher tier sleep', '' } },
            { group = 'SPECIAL STATES', cells = { '17', 'Charm', 'Mind control', 'BeastMaster test' } },
            { group = 'SPECIAL STATES', cells = { '32', 'Hide', 'Invisible to most mobs', '' } },
            { group = 'SPECIAL STATES', cells = { '87', 'Encumbrance', 'Cannot use items', '' } },
        },
    },
    {
        name = 'Trusts',
        note = 'Spell IDs for !trustengage <spellid>. Workbook note: IDs are approximate; verify with the Trust spells SQL lookup.',
        columns = { 'Spell ID', 'Trust Name', 'Role / Job', 'Notes' },
        widths = { 60, 130, 260, 200 },
        use = 1,
        copy = 1,
        rows = {
            { group = 'EARLY / STARTER TRUSTS', cells = { '896', 'Trion', 'PLD', 'Star Charter quest reward' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '897', 'Pieuje', 'WHM', 'Star Charter quest reward' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '898', 'Ayame', 'SAM', '' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '899', 'Curilla', 'PLD', '' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '900', 'Volker', 'WAR', '' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '901', 'Naji', 'WAR', '' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '902', 'Aldo', 'THF', '' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '903', 'Nanaa Mihgo', 'THF', '' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '904', 'Maat', 'MNK/all', 'Legendary trainer' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '905', 'Valaineral', 'PLD', '' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '906', 'Joachim', 'BRD', '' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '907', 'Najelith', 'RDM', '' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '908', 'Karaha-Baruha', 'SMN', '' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '909', 'Rahal', 'PLD', '' } },
            { group = 'EARLY / STARTER TRUSTS', cells = { '910', 'Koru-Moru', 'RDM', 'Excellent Refresh/Haste' } },
            { group = 'ADVENTURING FELLOWS / ICONIC', cells = { '911', 'Ulmia', 'BRD', 'Songs' } },
            { group = 'ADVENTURING FELLOWS / ICONIC', cells = { '912', 'Tenzen', 'SAM/NIN', '' } },
            { group = 'ADVENTURING FELLOWS / ICONIC', cells = { '913', 'Mihli Aliapoh', 'WHM', '' } },
            { group = 'ADVENTURING FELLOWS / ICONIC', cells = { '914', 'Prishe', 'MNK', 'CoP main char' } },
            { group = 'ADVENTURING FELLOWS / ICONIC', cells = { '915', 'Nashmeira', 'PUP', '' } },
            { group = 'ADVENTURING FELLOWS / ICONIC', cells = { '916', 'Lilisette', 'DNC', '' } },
            { group = 'ADVENTURING FELLOWS / ICONIC', cells = { '917', 'Lion', 'THF', '' } },
            { group = 'ADVENTURING FELLOWS / ICONIC', cells = { '918', 'Zeid II', 'DRK', '' } },
            { group = 'ADVENTURING FELLOWS / ICONIC', cells = { '919', 'Iroha', 'SAM', '' } },
            { group = 'ADVENTURING FELLOWS / ICONIC', cells = { '920', 'Arciela', 'RDM', '' } },
            { group = 'LATE-GAME / MEME TRUSTS', cells = { '921', 'Apururu (UC)', 'WHM', 'Cure V haste tank' } },
            { group = 'LATE-GAME / MEME TRUSTS', cells = { '922', 'Selh\'teus', 'BLM', '' } },
            { group = 'LATE-GAME / MEME TRUSTS', cells = { '923', 'Kupipi', 'WHM', '' } },
            { group = 'LATE-GAME / MEME TRUSTS', cells = { '924', 'Cornelia', 'PUP', '' } },
            { group = 'LATE-GAME / MEME TRUSTS', cells = { '925', 'Naja Salaheem', 'BST', '' } },
            { group = 'LATE-GAME / MEME TRUSTS', cells = { '926', 'Halver', 'MNK', '' } },
            { group = 'LATE-GAME / MEME TRUSTS', cells = { '927', 'Excenmille', 'PLD', '' } },
            { group = 'ASTRONOMICALLY USEFUL FOR YOUR TESTING', cells = { '898', 'Ayame', 'Tanky melee — good as a target dummy for testing', '' } },
            { group = 'ASTRONOMICALLY USEFUL FOR YOUR TESTING', cells = { '909', 'Rahal', 'Paladin tank — pulls aggro, takes hits', 'PartyVoice debuff dedup test' } },
            { group = 'ASTRONOMICALLY USEFUL FOR YOUR TESTING', cells = { '910', 'Koru-Moru', 'Refresh + Haste = sustained MP for spell tests', '' } },
            { group = 'ASTRONOMICALLY USEFUL FOR YOUR TESTING', cells = { '921', 'Apururu (UC)', 'Cure V + Erase chains for healing event triggers', '' } },
        },
    },
    {
        name = 'Weather',
        note = 'Weather IDs for !setweather <id>. Not all weather types are valid in every zone.',
        columns = { 'ID', 'Weather Name', 'Notes' },
        widths = { 50, 140, 200 },
        use = 1,
        copy = 1,
        rows = {
            { group = '', cells = { '0', 'None / Clear', 'Default' } },
            { group = '', cells = { '1', 'Sunshine', 'Boosts Fire/Light' } },
            { group = '', cells = { '2', 'Clouds', '' } },
            { group = '', cells = { '3', 'Fog', 'Earth-tinted' } },
            { group = '', cells = { '4', 'Hot Spell', 'Single Fire' } },
            { group = '', cells = { '5', 'Heat Wave', 'Double Fire' } },
            { group = '', cells = { '6', 'Rain', 'Single Water' } },
            { group = '', cells = { '7', 'Squall', 'Double Water' } },
            { group = '', cells = { '8', 'Dust Storm', 'Single Earth' } },
            { group = '', cells = { '9', 'Sand Storm', 'Double Earth' } },
            { group = '', cells = { '10', 'Wind', 'Single Wind' } },
            { group = '', cells = { '11', 'Gales', 'Double Wind' } },
            { group = '', cells = { '12', 'Snow', 'Single Ice' } },
            { group = '', cells = { '13', 'Blizzards', 'Double Ice' } },
            { group = '', cells = { '14', 'Thunder', 'Single Lightning' } },
            { group = '', cells = { '15', 'Thunderstorm', 'Double Lightning' } },
            { group = '', cells = { '16', 'Auroras', 'Single Light' } },
            { group = '', cells = { '17', 'Stellar Glare', 'Double Light' } },
            { group = '', cells = { '18', 'Gloom', 'Single Dark' } },
            { group = '', cells = { '19', 'Darkness', 'Double Dark' } },
        },
    },
    {
        name = 'Missions',
        note = 'Log IDs for !addmission <logid> <missionid> and related commands.',
        columns = { 'Log ID', 'Name', 'Description' },
        widths = { 60, 240, 240 },
        use = 1,
        copy = 1,
        rows = {
            { group = 'BASE GAME — NATION MISSIONS', cells = { '0', 'San d\'Oria Missions', 'Rank 1-10 nation storyline' } },
            { group = 'BASE GAME — NATION MISSIONS', cells = { '1', 'Bastok Missions', 'Rank 1-10 nation storyline' } },
            { group = 'BASE GAME — NATION MISSIONS', cells = { '2', 'Windurst Missions', 'Rank 1-10 nation storyline' } },
            { group = 'RISE OF THE ZILART', cells = { '3', 'Rise of the Zilart Missions', 'Post-rank 6 nation storyline' } },
            { group = 'CHAINS OF PROMATHIA', cells = { '4', 'Chains of Promathia Missions', 'Chapter-based storyline' } },
            { group = 'TREASURES OF AHT URHGAN', cells = { '5', 'Treasures of Aht Urhgan Missions', 'Aht Urhgan main storyline' } },
            { group = 'TREASURES OF AHT URHGAN', cells = { '6', 'Assault Missions', 'Periodic assault content' } },
            { group = 'WINGS OF THE GODDESS', cells = { '7', 'Wings of the Goddess Missions', 'WoTG main storyline' } },
            { group = 'WINGS OF THE GODDESS', cells = { '8', 'Campaign', 'Campaign battle missions' } },
            { group = 'ADD-ON SCENARIOS', cells = { '9', 'A Crystalline Prophecy', 'Ronfaure scenario' } },
            { group = 'ADD-ON SCENARIOS', cells = { '10', 'A Moogle Kupo d\'Etat', 'Moogle scenario' } },
            { group = 'ADD-ON SCENARIOS', cells = { '11', 'A Shantotto Ascension', 'Shantotto scenario' } },
            { group = 'ABYSSEA', cells = { '12', 'Vision of Abyssea', 'Abyssea Vision' } },
            { group = 'ABYSSEA', cells = { '13', 'Scars of Abyssea', 'Abyssea Scars' } },
            { group = 'ABYSSEA', cells = { '14', 'Heroes of Abyssea', 'Abyssea Heroes' } },
            { group = 'SEEKERS OF ADOULIN', cells = { '15', 'Seekers of Adoulin Missions', 'Adoulin main storyline' } },
            { group = 'RHAPSODIES OF VANA\'DIEL', cells = { '16', 'Rhapsodies of Vana\'diel Missions', 'RoV main storyline' } },
        },
    },
    {
        name = 'Skillchains',
        note = 'Skillchain names, elements and attribute combos (for skillchain testing).',
        columns = { 'Skillchain', 'Elements', 'Attribute Combo', 'Notes' },
        widths = { 120, 170, 220, 180 },
        use = nil,
        copy = 1,
        rows = {
            { group = 'LEVEL 1 SKILLCHAINS', cells = { 'Transfixion', 'Light', 'Distortion + Compression', 'Compression+Distortion' } },
            { group = 'LEVEL 1 SKILLCHAINS', cells = { 'Compression', 'Dark', 'Detonation + Distortion', 'Closes with Distortion' } },
            { group = 'LEVEL 1 SKILLCHAINS', cells = { 'Liquefaction', 'Fire', 'Impaction + Reverberation', 'Impaction+Reverberation' } },
            { group = 'LEVEL 1 SKILLCHAINS', cells = { 'Scission', 'Earth', 'Liquefaction + Detonation', 'Earth element' } },
            { group = 'LEVEL 1 SKILLCHAINS', cells = { 'Reverberation', 'Water', 'Induration + Impaction', 'Water element' } },
            { group = 'LEVEL 1 SKILLCHAINS', cells = { 'Detonation', 'Wind', 'Compression + Detonation', 'Wind element' } },
            { group = 'LEVEL 1 SKILLCHAINS', cells = { 'Induration', 'Ice', 'Reverberation + Liquefaction', 'Ice element' } },
            { group = 'LEVEL 1 SKILLCHAINS', cells = { 'Impaction', 'Thunder', 'Detonation + Liquefaction', 'Lightning element' } },
            { group = 'LEVEL 2 SKILLCHAINS', cells = { 'Gravitation', 'Earth+Dark', 'Distortion + Scission', 'Closes Darkness' } },
            { group = 'LEVEL 2 SKILLCHAINS', cells = { 'Distortion', 'Ice+Water', 'Gravitation + Fragmentation', 'Closes Darkness' } },
            { group = 'LEVEL 2 SKILLCHAINS', cells = { 'Fragmentation', 'Wind+Thunder', 'Detonation + Impaction', 'Closes Light' } },
            { group = 'LEVEL 2 SKILLCHAINS', cells = { 'Fusion', 'Fire+Light', 'Liquefaction + Impaction', 'Closes Light' } },
            { group = 'LEVEL 3 (BURSTING) SKILLCHAINS', cells = { 'Light', 'Fire+Wind+Thunder+Light', 'Fusion + Fragmentation', 'Magic burst Light' } },
            { group = 'LEVEL 3 (BURSTING) SKILLCHAINS', cells = { 'Darkness', 'Earth+Water+Ice+Dark', 'Gravitation + Distortion', 'Magic burst Dark' } },
            { group = 'LEVEL 4 (RADIANCE/UMBRA)', cells = { 'Radiance', 'Pure Light', 'Light + Light', 'Top-tier light chain' } },
            { group = 'LEVEL 4 (RADIANCE/UMBRA)', cells = { 'Umbra', 'Pure Dark', 'Darkness + Darkness', 'Top-tier dark chain' } },
        },
    },
    {
        name = 'Test Recipes',
        note = 'Command sequences for addon testing. Copy puts the command text on the clipboard.',
        columns = { 'Step', 'Commands', 'Expected Behavior' },
        widths = { 190, 330, 260 },
        use = nil,
        copy = 2,
        rows = {
            { group = '', cells = { 'Setup', '!addallmaps\n!addallwarps\n!setplayerlevel 75\n!capallskills\n!immortal', '' } },
            { group = '', cells = { 'Test 1: City group continuity', '!zone 234 (Bastok Mines)\n!zone 235 (Bastok Markets)\n!zone 236 (Port Bastok)\n!zone 237 (Metalworks)', 'Should play same city BGM continuously' } },
            { group = '', cells = { 'Test 2: Forced music override', '!setmusic 0 213 (force a specific track)', 'Test ZoneMusic override behavior' } },
            { group = '', cells = { 'Test 3: Dungeon transitions', '!zone 165 (Crawlers\' Nest)\n!zone 234 (Bastok Mines)', 'Verify dungeon→city transition' } },
            { group = 'SCVoice — Skillchain detection', cells = { 'Setup', '!addalltrusts\n!addallweaponskills\n!capallskills\n!setplayerlevel 75', '' } },
            { group = 'SCVoice — Skillchain detection', cells = { 'Spawn pet to feed TP', '!spawnmob <weak_mob_id>\n!hp 0 to reset between tests', '' } },
            { group = 'SCVoice — Skillchain detection', cells = { 'Trust skillchain combo', 'Cast Trust: Trion and Apururu (UC)\nEngage mob\nLet them close skillchain naturally', 'Light skillchain trigger' } },
            { group = 'SCVoice — Skillchain detection', cells = { 'Manual skillchain', '!tp 3000\nEngage mob, use WS\n!tp 3000\nUse closing WS', 'Test specific SC names' } },
            { group = 'PartyVoice — Party event audio', cells = { 'Setup', '!addalltrusts\n!setplayerlevel 75\n!capallskills\n!immortal', '' } },
            { group = 'PartyVoice — Party event audio', cells = { 'Spawn full trust party', 'Cast 5 trust spells (e.g. Trion, Apururu, Koru-Moru, Joachim, Iroha)', '5 trusts + you = full party' } },
            { group = 'PartyVoice — Party event audio', cells = { 'Trigger AoE debuff', '!spawnmob <aoe_caster> (e.g. a dragon)\nLet it use breath attacks', 'PartyVoice should dedup AoE debuffs' } },
            { group = 'PartyVoice — Party event audio', cells = { 'Trigger heal events', '!hp 1 then have Apururu cure you', '' } },
            { group = 'PartyVoice — Party event audio', cells = { 'Trigger KO events', 'Disable !immortal\n!hp 0 on a trust\nThen !hp 0 self', 'KO audio should fire' } },
            { group = 'BeastVoice — Pet/charm audio', cells = { 'Setup', '!changejob bst\n!setplayerlevel 75\n!capallskills\n!immortal\n!addallspells (for charm)', '' } },
            { group = 'BeastVoice — Pet/charm audio', cells = { 'Charm test', 'Find a charmable mob (most low-tier outdoor mobs)\nUse Charm\nObserve charm/release events', 'BeastVoice should fire on charm/release' } },
            { group = 'BeastVoice — Pet/charm audio', cells = { 'Pet TP move test', 'With charmed pet, fight mob\n!pettp 100 to force TP move', 'Verify TP move audio dedup' } },
            { group = 'BeastVoice — Pet/charm audio', cells = { 'Pet KO test', 'Let pet die, observe death audio', '' } },
            { group = 'BardVoice — Song casting audio', cells = { 'Setup', '!changejob brd\n!setplayerlevel 75\n!capallskills\n!addallspells', '' } },
            { group = 'BardVoice — Song casting audio', cells = { 'Cast various songs', 'Cycle through different song types: ballads, marches, mambos, etudes', 'Each song family should have unique audio' } },
            { group = 'BardVoice — Song casting audio', cells = { 'Overlapping songs', 'Cast two songs (max bard songs)\nTry casting a third (overwrites first)', 'Test song-replace event' } },
            { group = 'EmoteVoice — Emote triggers', cells = { 'Setup', 'Any character state with chat working', '' } },
            { group = 'EmoteVoice — Emote triggers', cells = { 'Cycle emotes', '/wave\n/bow\n/cheer\n/laugh\n/cry\n/poke\n/dance\n/joy', 'Each should fire EmoteVoice' } },
            { group = 'EmoteVoice — Emote triggers', cells = { 'Target-directed emotes', '/wave <Moonrise>\n/poke <NPC>', 'Test targeted vs self emotes' } },
            { group = 'EmoteVoice — Emote triggers', cells = { 'Motion-only emotes', '/wave motion (no text)', 'Test text vs motion variant audio' } },
        },
    },
    {
        name = 'SQL Lookups',
        note = 'Queries for an external database tool (HeidiSQL). REFERENCE ONLY: GMPanel never connects to a database or runs SQL.',
        columns = { 'Purpose', 'SQL Query' },
        widths = { 230, 560 },
        use = nil,
        copy = 2,
        rows = {
            { group = 'MOBS / ENEMIES', cells = { 'MOB ID', 'SELECT mobid, mobname, polutils_name, minLevel, maxLevel\nFROM mob_spawn_points\nWHERE mobname LIKE \'%behemoth%\'\nORDER BY mobname;' } },
            { group = 'MOBS / ENEMIES', cells = { 'Find mob (pool) by name', 'SELECT poolid, name, mJob, sJob, mobType, spellList FROM mob_pools WHERE name LIKE \'%dragon%\' ORDER BY name;' } },
            { group = 'MOBS / ENEMIES', cells = { 'Find mob with level (spawn points)', 'SELECT mobid, mobname, polutils_name, minLevel, maxLevel, pos_x, pos_y, pos_z FROM mob_spawn_points WHERE mobname LIKE \'%fafnir%\';' } },
            { group = 'MOBS / ENEMIES', cells = { 'Find mob groups (zone, HP/MP, respawn)', 'SELECT groupid, poolid, zoneid, name, respawntime, HP, MP FROM mob_groups WHERE name LIKE \'%dragon%\' ORDER BY zoneid;' } },
            { group = 'MOBS / ENEMIES', cells = { 'All mobs in a zone (via groups)', 'SELECT groupid, name, HP, MP FROM mob_groups WHERE zoneid = 145 ORDER BY name;' } },
            { group = 'ITEMS', cells = { 'Find item by name', 'SELECT itemid, name, type, stackSize FROM item_basic WHERE name LIKE \'%potion%\' ORDER BY itemid;' } },
            { group = 'ITEMS', cells = { 'Find weapon by name', 'SELECT w.* FROM item_weapon w JOIN item_basic b ON b.itemid = w.itemid WHERE b.name LIKE \'%sword%\';' } },
            { group = 'ITEMS', cells = { 'Find armor/equipment by name', 'SELECT e.* FROM item_equipment e JOIN item_basic b ON b.itemid = e.itemid WHERE b.name LIKE \'%relic%\';' } },
            { group = 'SPELLS', cells = { 'Find spell by name', 'SELECT spellid, name, jobs, skill, mpCost FROM spell_list WHERE name LIKE \'%cure%\' ORDER BY spellid;' } },
            { group = 'Find spells for a job (bit; WHM=6)', cells = { 'Trust spells', 'SELECT spellid, name FROM spell_list WHERE content_tag = \'TRUST\' OR name LIKE \'Trust:%\' ORDER BY name;' } },
            { group = 'Find spells for a job (bit; WHM=6)', cells = { 'Spells by element (e.g. element=1 fire)', 'SELECT spellid, name, element FROM spell_list WHERE element = 1 ORDER BY spellid;' } },
            { group = 'Zone settings (real columns)', cells = { 'Zone music tracks (real columns)', 'SELECT zoneid, name, music_day, music_night, battlesolo, battlemulti FROM zone_settings WHERE zoneid = 145;' } },
            { group = 'CHARACTER (Moonrise)', cells = { 'Your character row', 'SELECT * FROM chars WHERE charname = \'Moonrise\';' } },
            { group = 'Mission / nation state (real columns)', cells = { 'Your spells', 'SELECT * FROM char_spells WHERE charid = (SELECT charid FROM chars WHERE charname=\'Moonrise\');' } },
            { group = 'Mission / nation state (real columns)', cells = { 'Your job levels', 'SELECT * FROM char_jobs WHERE charid = (SELECT charid FROM chars WHERE charname=\'Moonrise\');' } },
            { group = 'Mission / nation state (real columns)', cells = { 'Reset stuck session', 'DELETE FROM accounts_sessions WHERE charid = (SELECT charid FROM chars WHERE charname=\'Moonrise\');' } },
            { group = 'List all tables', cells = { 'Describe a table (ALWAYS do this first)', 'DESCRIBE mob_pools;' } },
            { group = 'List all tables', cells = { 'Backup chars (run in cmd, not SQL)', 'mysqldump -u root -p5726 xidb chars > chars_backup.sql' } },
            { group = 'List all tables', cells = { 'Restore chars (run in cmd, not SQL)', 'mysql -u root -p5726 xidb < chars_backup.sql' } },
        },
    },
};

return data;
